### ISSUE TITLE
tooltip reporting incorrect training available

### ISSUE THREAD

**Issue by Noesis-Boss** [ps-wow/Broker_Classic_Training#22] opened 2019-10-08 21:26 UTC
![broker_training_classic](https://user-images.githubusercontent.com/10440510/66434559-a828d700-e9d7-11e9-990c-b3431b6cce49.jpg)

**Comment by davidcraig** [comment] 2019-10-20 09:40
Hi, what level was this paladin?

**Comment by Noesis-Boss** [comment] 2019-10-20 13:27
now he's 44, was 40 at the time

**Comment by davidcraig** [comment] 2019-10-20 13:29
two thoughts I have, is this similar to how warrior spells don't downrank, so you presumably have devotion aura rank 5, and that is the only spell you have in your book, which is why 1-4 are showing like this?

**Comment by davidcraig** [comment] 2019-10-20 13:29
parry will be because the spell id I noted was the wrong one (parry has multiple spell id's).

**Comment by davidcraig** [comment] 2019-10-22 12:09
I have fixed the spell id for parry, so this should have been resolved in the latest alpha version, I will create a tagged release later for download.  In terms of the other spells listed, would you be able to provide screenshots from the spellbook, I am guessing when you learn devotion aura rank 2, it replaces rank 1, etc, is this true for all the spells listed in your screenshot?

**Comment by davidcraig** [comment] 2019-11-01 11:07
I have confirmed the behaviour of Devotion Aura, it would seem as a generic note across classic in general that spells with mana are able to be downranked, spells with zero cost or rage/energy etc seem to automatically use the latest version, I will use this to update the replaced by functionality across the board.

**Closed as completed** 2021-05-07 22:57 UTC
Labels: Paladin
